language: java
cache:
  directories:
  - $HOME/.m2/repository

sudo: required

jdk:
  - oraclejdk8

# By default Travis will install dependencies before it runs a build, and with Maven projects that
# means running an install build without tests. We don't need to do this, and it actually causes problems.
# So skip it...
install: true

script:
  - mvn clean package
